blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('accounts/',include('allauth.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from .views import CommentDeleteView, PostCreateView, PostDetailView, PostListView, PostUpdateView, PostDeleteView, PostLikeView, CommentView, CommentDeleteView, UsersPostListView

app_name='posts'

urlpatterns = [
    path('',PostListView.as_view(),name='home'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-detail'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('post/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('like/<int:pk>/',PostLikeView,name='post-like'),
    path('comment/<int:pk>/add/',CommentView.as_view(),name='comment'),
    path('comment/<int:pk>/delete/',CommentDeleteView.as_view(),name='comment-delete'),
    path('user/<str:username>', UsersPostListView.as_view(), name='user-post'),
]

posts/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=500)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_image',null=True,blank=True)
    likes = models.ManyToManyField(User,related_name='post_likes')

    def __str__(self) -> str:
        return self.title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('posts:post-detail',kwargs={'pk':self.pk})

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User,on_delete=models.CASCADE) 
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return (f'{self.post.title} by {self.name}')

posts/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse, reverse_lazy
from .models import Post, Comment
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
# Create your views here.


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    ordering = '-date_created'
    template_name = 'posts/home.html'

class UsersPostListView(ListView):
    model = Post
    context_object_name = 'posts'
    ordering = '-date_created'
    template_name = 'posts/user_post.html'

    def get_queryset(self):
        user = get_object_or_404(User,username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_created')


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        context['total_likes'] = stuff.total_likes()
        return context

class PostCreateView(CreateView):
    model = Post
    template_name = 'posts/createupdate.html'
    fields = ['title','content','image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'posts/createupdate.html'
    fields = ['title','content','image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False
            
class PostDeleteView(DeleteView):
    model = Post
    success_url = '/'
    template_name = 'posts/delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False
    

def PostLikeView(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if not request.user in post.likes.all():
        post.likes.add(request.user)
        # return HttpResponseRedirect(reverse('posts:post-detail', args=[str(pk)]))
        return redirect(request.META['HTTP_REFERER'])
    else:
        post.likes.remove(request.user)
        # return HttpResponseRedirect(reverse('posts:post-detail', args=[str(pk)]))
        return redirect(request.META['HTTP_REFERER'])
    # return HttpResponseRedirect(reverse('posts:post-detail', args=[str(pk)]))



class CommentView(CreateView):
    model = Comment
    template_name = 'posts/comment.html'
    fields = ["body"]

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.name = self.request.user
        # form.instance.post = Post.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse_lazy('posts:post-detail',kwargs={'pk':self.kwargs['pk']})


class CommentDeleteView(DeleteView):
    model= Comment
    template_name = 'posts/comment.html'

    def test_func(self):
        comment = get_objects()
        if comment.name == self.request.user:
            return True
        else:
            return False
    
    def get_success_url(self):
        post = get_object_or_404(Post,id=self.request.POST.get('post_id'))
        return reverse_lazy('posts:post-detail', kwargs={'pk':post.id})

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="">Profile</a>
                <a class="nav-item nav-link" href="{% url 'account_logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'account_signup' %}">Register</a>
                <a class="nav-item nav-link" href="{% url 'account_login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
      <main class="container" role="main">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                {% block content %}{% endblock content %}
            </div>
        </div>
      </main>
      <footer class="position-relative width-100% py-3">
        <div class="text-light bg-dark text-center">Footer &copy; 2022</div>

      </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

posts/templates/posts/comment.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Comment</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Comment</button>
            </div>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/createupdate.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if object.id %}
    <label for="update">Update</label>
    {% else %}
    <label for="new">New</label>
    {% endif %}
    {{ form|crispy }}
    <button class="btn btn-primary btn-sm my-2" type="submit">Submit</button>
</form>


{% endblock content %}

posts/templates/posts/delete.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <label for="update">Do you want to delete <a href="{% url 'posts:post-detail' object.id %}">{{ object.title }} </a>?</label>
    {{ form|crispy }}
    <button class="btn btn-primary btn-sm my-2" type="submit">Submit</button>
</form>


{% endblock content %}

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% if object.author == request.user %}
<span>
    <a class="btn btn-success btn-sm" href="{% url 'posts:post-update' object.id %}" >Update</a>
    <a class="btn btn-danger btn-sm" href="{% url 'posts:post-delete' object.id %}" >Delete</a>  
</span>
{% endif %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="#">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted | date:"F d,Y" }}</small>
      </div>
      <h2><a class="article-title" href="{% url 'posts:post-detail' object.id %}">{{ object.title }}</a></h2>
      <p class="article-content">{{ object.content }}</p>
      {% if object.image %}
      <div><img src="{{ object.image.url }}" alt="" height="auto" width="100%"></div>
      {% else %}
      <div></div>
      {% endif %}
    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'posts:post-like' object.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in object.likes.all %}
      <button type="submit" name="post_id", value="{{ object.id }}", class="btn btn-red my-2"> <i class="fa fa-heart" aria-hidden="true">Dislike</i></button> <span class="text-muted">{{ object.total_likes }}</span>
      {% else %}
      <button type="submit" name="post_id", value="{{ object.id }}", class="btn btn-white my-2"><i class="fa fa-heart-o" aria-hidden="true">Like</i> </button> <span class="text-muted">{{ object.total_likes }}</span>
      {% endif %}
    </form>
    {% else %}
      <a class="btn btn-primary", href="{% url 'account_login' %}">Login & Like!</a>
    {% endif %}

    <hr/>
    <h2>Comments</h2>
        {% if not object.comments.all %}
          Not yet comment <a href="{% url 'posts:comment' object.pk %}">Add one</a>
        {% else %}
          {% for comment in object.comments.all %}
            <br/>
        <strong>{{ comment.name }} - {{ comment.date_added }}</strong> <br/>
        {{ comment.body }}
        <span>
            <form action="{% url 'posts:comment-delete' comment.id %}" method="post">
            {% csrf_token %}
            <button name="post_id" value="{{ object.id }}" class="btn btn-danger btn-sm" type="submit">Delete</button>
            </form>
    </span>
          {% endfor %}
        <br/>
          <a href="{% url 'posts:comment' object.pk %}">New Comment</a>
        {% endif %}

    
</article>



{% endblock content %}

posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% for post in posts %}
<article class="media content-section border my-2">
    <img class="rounded-circle article-img" src="#">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'posts:user-post' post.author.username %}">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted | date:"F d,Y" }}</small>
      </div>
      <h2><a class="article-title" href="{% url 'posts:post-detail' post.id %}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>

    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'posts:post-like' post.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in post.likes.all %}
      <button type="submit" name="post_id", value="{{ post.id }}", class="btn btn-red my-2"> <i class="fa fa-heart" aria-hidden="true">Dislike</i></button> <span class="text-muted">{{ post.total_likes }}</span>
      {% else %}
      <button type="submit" name="post_id", value="{{ post.id }}", class="btn btn-white my-2"><i class="fa fa-heart-o" aria-hidden="true">Like</i> </button> <span class="text-muted">{{ post.total_likes }}</span>
      {% endif %}
    </form>
    {% else %}
      <a class="btn btn-primary", href="{% url 'account_login' %}">Login & Like!</a>
    {% endif %}
</article>

{% endfor %}

{% endblock content %}

posts/templates/posts/user_post.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="#">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted | date:"F d,Y" }}</small>
      </div>
      <h2><a class="article-title" href="{% url 'posts:post-detail' post.id %}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>

    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'posts:post-like' post.pk %}" method="POST">
      {% csrf_token %}
      {% if post.total_likes %}
      <button type="submit" name="post_id", value="{{ post.id }}", class="btn btn-success py-2">Like {{ post.total_likes }} </button>
      {% else %}
      <button type="submit" name="post_id", value="{{ post.id }}", class="btn btn-primary py-2">Like {{ post.total_likes }} </button>
      {% endif %}
    </form>
    {% else %}
      <a class="btn btn-primary", href="{% url 'login' %}">Login & Like!</a>
    {% endif %}
</article>

{% endfor %}

{% endblock content %}